name: vote_app_-_build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_WRITETOKEN }}
        registry: ghcr.io
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./azure-vote/.
        file: ./azure-vote/Dockerfile
        push: true
        tags: ghcr.io/vergiet/azure-vote:latest, ghcr.io/vergiet/azure-vote:0.1.0

